// app/page.js
'use client';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { 
  MessageSquare, 
  Users, 
  Award, 
  Zap, 
  Shield, 
  TrendingUp,
  ChevronRight,
  Star,
  ArrowRight,
  Sparkles,
  Brain,
  Trophy,
  BarChart3
} from 'lucide-react';
import Header from './components/Header';

export default function Home() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const router = useRouter();

  useEffect(() => {
    const token = localStorage.getItem('token');
    setIsLoggedIn(!!token);
  }, []);

  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Questions',
      description: 'Get smart questions generated by ML algorithms based on topics and difficulty levels.'
    },
    {
      icon: Trophy,
      title: 'Expertise System',
      description: 'Earn points, level up, and become an expert in your favorite topics.'
    },
    {
      icon: Users,
      title: 'Organization Hub',
      description: 'Create or join organizations to learn and compete with teams.'
    },
    {
      icon: BarChart3,
      title: 'Performance Analytics',
      description: 'Track your progress with detailed statistics and leaderboards.'
    },
    {
      icon: Shield,
      title: 'Verified Experts',
      description: 'Our verification system ensures quality answers from trusted experts.'
    },
    {
      icon: Zap,
      title: 'Real-time Updates',
      description: 'Get instant feedback on your answers and watch your points grow.'
    }
  ];

  const stats = [
    { value: '10K+', label: 'Active Users' },
    { value: '50K+', label: 'Questions Answered' },
    { value: '1K+', label: 'Verified Experts' },
    { value: '95%', label: 'Satisfaction Rate' }
  ];

  const testimonials = [
    {
      name: 'Sarah Johnson',
      role: 'Software Developer',
      content: 'The expertise system really motivated me to learn more. Becoming an expert in JavaScript was so rewarding!',
      rating: 5
    },
    {
      name: 'Michael Chen',
      role: 'Data Scientist',
      content: 'The ML-generated questions are surprisingly good. It feels like having a personal tutor.',
      rating: 5
    },
    {
      name: 'Emily Rodriguez',
      role: 'Product Manager',
      content: 'Our team uses this for training. The organization features are perfect for team learning.',
      rating: 5
    }
  ];

  return (
    <>
      <Header />
      
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-[#F0EFFF] via-white to-[#EEF2FF] py-20">
        <div className="container mx-auto px-6">
          <div className="max-w-4xl mx-auto text-center">
            <div className="inline-flex items-center gap-2 bg-[#F3F2FF] rounded-full px-4 py-1.5 mb-6">
              <Sparkles size={14} className="text-[#6C63FF]" />
              <span className="text-xs font-medium text-[#6C63FF]">AI-Powered Learning Platform</span>
            </div>
            <h1 className="text-5xl md:text-6xl font-bold text-[#2D2A5A] mb-6 leading-tight">
              Master Any Topic,
              <span className="text-[#6C63FF]"> Earn Expertise</span>
            </h1>
            <p className="text-lg text-[#7A799D] mb-8 max-w-2xl mx-auto">
              Test your knowledge with AI-generated questions, earn points, and become a verified expert in your field.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              {!isLoggedIn ? (
                <>
                  <Link
                    href="/register"
                    className="px-8 py-3 bg-gradient-to-r from-[#6C63FF] to-[#9C8FFF] text-white rounded-lg hover:from-[#5550E8] hover:to-[#8A7FEE] transition-colors text-sm font-medium inline-flex items-center justify-center gap-2"
                  >
                    Start Learning Free
                    <ChevronRight size={16} />
                  </Link>
                  <Link
                    href="/login"
                    className="px-8 py-3 border border-[#E0DEFF] text-[#6C63FF] rounded-lg hover:bg-[#F5F4FF] hover:border-[#CFCBFF] transition-colors text-sm font-medium"
                  >
                    Sign In
                  </Link>
                </>
              ) : (
                <Link
                  href="/dashboard"
                  className="px-8 py-3 bg-gradient-to-r from-[#6C63FF] to-[#9C8FFF] text-white rounded-lg hover:from-[#5550E8] hover:to-[#8A7FEE] transition-colors text-sm font-medium inline-flex items-center justify-center gap-2"
                >
                  Go to Dashboard
                  <ArrowRight size={16} />
                </Link>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-16 bg-white border-y border-[#F0EEFF]">
        <div className="container mx-auto px-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat, index) => (
              <div key={index} className="text-center">
                <div className="text-3xl md:text-4xl font-bold text-[#4B48A3] mb-2">
                  {stat.value}
                </div>
                <div className="text-sm text-[#7A799D]">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-20 bg-[#F5F4FF]">
        <div className="container mx-auto px-6">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-[#2D2A5A] mb-4">
              Powerful Learning Features
            </h2>
            <p className="text-lg text-[#7A799D] max-w-2xl mx-auto">
              Everything you need to test knowledge, track progress, and become an expert
            </p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <div key={index} className="bg-white rounded-xl p-6 border border-[#E6E4FF] hover:shadow-lg transition-all">
                  <div className="w-12 h-12 bg-[#F5F4FF] rounded-lg flex items-center justify-center mb-4">
                    <Icon size={22} className="text-[#6C63FF]" />
                  </div>
                  <h3 className="text-lg font-semibold text-[#2D2A5A] mb-2">
                    {feature.title}
                  </h3>
                  <p className="text-sm text-[#7A799D] leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section id="testimonials" className="py-20 bg-white">
        <div className="container mx-auto px-6">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-[#2D2A5A] mb-4">
              What Our Users Say
            </h2>
            <p className="text-lg text-[#7A799D] max-w-2xl mx-auto">
              Join thousands of satisfied learners mastering new skills
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            {testimonials.map((testimonial, index) => (
              <div key={index} className="bg-[#F5F4FF] rounded-xl p-6 border border-[#E6E4FF]">
                <div className="flex gap-1 mb-4">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star key={i} size={14} className="fill-[#6C63FF] text-[#6C63FF]" />
                  ))}
                </div>
                <p className="text-[#6B6A8F] text-sm mb-4 leading-relaxed">"{testimonial.content}"</p>
                <div>
                  <p className="font-semibold text-sm text-[#2D2A5A]">{testimonial.name}</p>
                  <p className="text-xs text-[#7A799D]">{testimonial.role}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-br from-[#F0EFFF] via-white to-[#EEF2FF]">
        <div className="container mx-auto px-6 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-[#2D2A5A] mb-4">
            Ready to Become an Expert?
          </h2>
          <p className="text-lg text-[#7A799D] mb-8 max-w-2xl mx-auto">
            Join our community of learners and start your journey to expertise today
          </p>
          {!isLoggedIn ? (
            <Link
              href="/register"
              className="inline-flex items-center gap-2 px-8 py-3 bg-gradient-to-r from-[#6C63FF] to-[#9C8FFF] text-white rounded-lg hover:from-[#5550E8] hover:to-[#8A7FEE] transition-colors text-sm font-medium"
            >
              Create Free Account
              <ArrowRight size={16} />
            </Link>
          ) : (
            <Link
              href="/dashboard"
              className="inline-flex items-center gap-2 px-8 py-3 bg-gradient-to-r from-[#6C63FF] to-[#9C8FFF] text-white rounded-lg hover:from-[#5550E8] hover:to-[#8A7FEE] transition-colors text-sm font-medium"
            >
              Go to Dashboard
              <ArrowRight size={16} />
            </Link>
          )}
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-white border-t border-[#F0EEFF] py-12">
        <div className="container mx-auto px-6">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="mb-4 md:mb-0">
              <Link href="/" className="text-xl font-bold text-[#6C63FF]">
                QnA Expert
              </Link>
              <p className="text-xs text-[#7A799D] mt-2">
                Master topics. Earn expertise. Grow together.
              </p>
            </div>
            <div className="flex space-x-6">
              <a href="#features" className="text-xs text-[#7A799D] hover:text-[#6C63FF] transition-colors">
                Features
              </a>
              <a href="#testimonials" className="text-xs text-[#7A799D] hover:text-[#6C63FF] transition-colors">
                Testimonials
              </a>
              <a href="#" className="text-xs text-[#7A799D] hover:text-[#6C63FF] transition-colors">
                Privacy
              </a>
              <a href="#" className="text-xs text-[#7A799D] hover:text-[#6C63FF] transition-colors">
                Terms
              </a>
            </div>
          </div>
          <div className="text-center text-xs text-[#7A799D] mt-8 pt-8 border-t border-[#F0EEFF]">
            © {new Date().getFullYear()} QnA Expert. All rights reserved.
          </div>
        </div>
      </footer>
    </>
  );
}